
SELECT 
	e.Level1ID, 
	l1.Level1Name,
	e.Level2ID, 
	l2.Level2Name,
	SUM(CASE WHEN hcMonth = 1 THEN HeadCount ELSE 0 END) [Jan],
	SUM(CASE WHEN hcMonth = 2 THEN HeadCount ELSE 0 END) [Feb],
	SUM(CASE WHEN hcMonth = 3 THEN HeadCount ELSE 0 END) [Mar]

FROM ExternalData e
JOIN OrgDataLevel1 l1 on e.Level1ID = l1.Level1ID
JOIN OrgDataLevel2 l2 on e.Level2ID = l2.Level2ID

WHERE hcYear = 2020 and e.Level2ID IS NOT NULL AND IsAutoGenerated = 1
GROUP BY e.Level1ID, l1.Level1Name, e.Level2ID, l2.Level2Name
ORDER BY l1.Level1Name, l2.Level2Name