SELECT
                GAEXPORT.CUSTNO,
                COMPANY,
                COLLECTOR,
                INVNO,
                GAEXPORT.AMOUNT,
                ACTION,
                OPERATION,
                GAEXPORT.RECEIPT_ID,
				GARECEIPT.RECEIPT_NUM,
                DEPOSIT_DATE,
                GAEXPORT.MODIFIED_ON,
                GADEPOSIT.CURRCODE,
                BASE_RATE,
				CASE WHEN ACTION = 'D' THEN GAEXPORT.AMOUNT / BASE_RATE ELSE GAEXPORT.AMOUNT / BASE_RATE * - 1 	END AS [8X AMT],
				CASE WHEN ACTION = 'C' THEN 0 - AMOUNT_BASE ELSE AMOUNT_BASE END AS [Dashboard Amt]
FROM gpcomp1.GAEXPORT GAEXPORT
LEFT OUTER JOIN gpcomp1.GARECEIPT GARECEIPT ON GAEXPORT.RECEIPT_ID = GARECEIPT.RECEIPT_ID
LEFT OUTER JOIN gpcomp1.GABATCH GABATCH ON GARECEIPT.BATCH_ID = GABATCH.BATCH_ID
LEFT OUTER JOIN gpcomp1.GADEPOSIT GADEPOSIT ON GABATCH.DEPOSIT_ID = GADEPOSIT.DEPOSIT_ID
INNER JOIN gpglobal.GPCURNCY GPCURNCY ON GADEPOSIT.CURRCODE = GPCURNCY.CURRCODE
LEFT OUTER JOIN gpcomp1.GPCUST GPCUST ON GAEXPORT.CUSTNO = GPCUST.CUSTNO
WHERE OPERATION = 6 AND gadeposit.deposit_date  >= CAST('2022-1-1' AS DATETIME)
