SELECT *,JASPER_REPORT_FILE_PDF, JASPER_REPORT_FILE_EXCEL
FROM gpcomp1.RWJASPER_REPORT_TABLE
WHERE REPORT_FILE_ID
IN (SELECT REPORT_FILE_ID FROM gpcomp1.RWREPORT_TABLE where JAVA_REPORT_DESC like '8x Weatherford Custom Dispute Report');

SELECT * FROM gpcomp1.RWREPORT_TABLE where JAVA_REPORT_DESC like '8x Weatherford Custom Dispute Report'