--BEGIN TRAN
sp_help 'gpcomp1.GPCOLTM'

INSERT INTO GPCOMP1.GPCOLTM (TEAM, Description, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY) VALUES ('EUA', 'Europe Africa', GETDATE(), 10866, getdate(), 10866)

INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'EUA AZ','EUA AZ', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'EUA BKY','EUA BKY', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'EUA CM','EUA CM', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'EUA DE','EUA DE', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'EUA DM','EUA DM', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'EUA EXPORT','EUA EXPORT', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'EUA IT','EUA IT', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'EUA Legal','EUA Legal', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'EUA NL','EUA NL', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'EUA NO','EUA NO', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'EUA PO','EUA PO', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'EUA RO','EUA RO', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'EUA SP','EUA SP', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'EUA UK_UK','EUA UK_UK', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA Angola','SSA Angola', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA CAMERO','SSA CAMERO', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA CHAD','SSA CHAD', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA CONGO','SSA CONGO', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA ET','SSA ET', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA GABON','SSA GABON', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA GHANA','SSA GHANA', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA GQ','SSA GQ', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA IVORYC','SSA IVORYC', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA KENYA','SSA KENYA', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA LIBER','SSA LIBER', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA MOZAMB','SSA MOZAMB', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA NAMBIA','SSA NAMBIA', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA NIGER','SSA NIGER', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA S AFR','SSA S AFR', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA SENEGL','SSA SENEGL', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA TANZ','SSA TANZ', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA UGANDA','SSA UGANDA', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)
INSERT INTO gpcomp1.GPCOLL (COLLCODE, COLLNAME, TEAM, CREATED_ON, CREATED_BY, MODIFIED_ON, MODIFIED_BY, USERLIC_ID) VALUES( 'SSA-ANGOLA','SSA-ANGOLA', 'EUA', GETDATE(), 10866, GETDATE(), 10866, 0)

UPDATE gpcomp1.gpcoll set team ='EUA' WHERE collcode = 'WAA'
UPDATE gpcomp1.gpcoll set team ='EUA' WHERE collcode = 'WAM'

UPDATE gpcomp1.gpcust SET Collector = 'SSA-ANGOLA' WHERE Collector ='WAA'
UPDATE gpcomp1.gpcust SET Collector = 'SSA-ANGOLA' WHERE Collector ='WA-ANGOLA2'
UPDATE gpcomp1.gpcust SET Collector = 'SSA ET' WHERE Collector ='ME - ET'
UPDATE gpcomp1.gpcust SET Collector = 'EUA BKY' WHERE Collector ='SSA_BKY'
UPDATE gpcomp1.gpcust SET Collector = 'EUA Legal' WHERE Collector ='SSA_LEGAL'
UPDATE gpcomp1.gpcust SET Collector = 'EUA EXPORT' WHERE Collector ='W AFR EXP'
UPDATE gpcomp1.gpcust SET Collector = 'SSA-ANGOLA' WHERE Collector ='WA-CABINDA'
UPDATE gpcomp1.gpcust SET Collector = 'SSA CAMERO' WHERE Collector ='WA-CAMEROO'
UPDATE gpcomp1.gpcust SET Collector = 'SSA CHAD' WHERE Collector ='WA-CHAD'
UPDATE gpcomp1.gpcust SET Collector = 'SSA CONGO' WHERE Collector ='WA_CONGO'
UPDATE gpcomp1.gpcust SET Collector = 'SSA GABON' WHERE Collector ='WA-GABON'
UPDATE gpcomp1.gpcust SET Collector = 'SSA GHANA' WHERE Collector ='WA-GHANA'
UPDATE gpcomp1.gpcust SET Collector = 'SSA GQ' WHERE Collector ='WA-GQ'
UPDATE gpcomp1.gpcust SET Collector = 'SSA IVORYC' WHERE Collector ='WA-IVORY C'
UPDATE gpcomp1.gpcust SET Collector = 'SSA MOZAMB' WHERE Collector ='WA-MOZAMBI'
UPDATE gpcomp1.gpcust SET Collector = 'SSA NAMBIA' WHERE Collector ='WA-NAMIBIA'
UPDATE gpcomp1.gpcust SET Collector = 'SSA NIGER' WHERE Collector ='WA-NIGERIA'
UPDATE gpcomp1.gpcust SET Collector = 'SSA S AFR' WHERE Collector ='WA-S AFRIC'
UPDATE gpcomp1.gpcust SET Collector = 'SSA SENEGL' WHERE Collector ='WA-SENEGAL'
UPDATE gpcomp1.gpcust SET Collector = 'SSA TANZ' WHERE Collector ='WA-TANZ'
UPDATE gpcomp1.gpcust SET Collector = 'SSA UGANDA' WHERE Collector ='WA-UGANDA'
UPDATE gpcomp1.gpcust SET Collector = 'WAA' WHERE Collector ='WAA_ WEST AFRICA Alpha'
UPDATE gpcomp1.gpcust SET Collector = 'WAM' WHERE Collector ='WAM _WEST AFRICA MAJor'
UPDATE gpcomp1.gpcust SET Collector = 'SSA KENYA' WHERE Collector ='WA_KENYA'
UPDATE gpcomp1.gpcust SET Collector = 'SSA LIBER' WHERE Collector ='WA_LIBERIA'
UPDATE gpcomp1.gpcust SET Collector = 'SSA NIGER' WHERE Collector ='WA_NG_LOC'
UPDATE gpcomp1.gpcust SET Collector = 'EUA CM' WHERE Collector ='WA_SCREENE'

UPDATE gpcomp1.gpcust SET Collector = 'EUA Legal' WHERE Collector ='CEU_legal'
UPDATE gpcomp1.gpcust SET Collector = 'EUA DE' WHERE Collector ='EU_DE'
UPDATE gpcomp1.gpcust SET Collector = 'EUA DM' WHERE Collector ='EU_DM'
UPDATE gpcomp1.gpcust SET Collector = 'EUA IT' WHERE Collector ='EU_IT'
UPDATE gpcomp1.gpcust SET Collector = 'EUA NL' WHERE Collector ='EU_NL'
UPDATE gpcomp1.gpcust SET Collector = 'EUA PO' WHERE Collector ='EU_PO'
UPDATE gpcomp1.gpcust SET Collector = 'EUA RO' WHERE Collector ='EU_RO'
UPDATE gpcomp1.gpcust SET Collector = 'EUA SP' WHERE Collector ='EU_SP'
UPDATE gpcomp1.gpcust SET Collector = 'EUA Legal' WHERE Collector ='EU-LEGAL'
UPDATE gpcomp1.gpcust SET Collector = 'EUA AZ' WHERE Collector ='CS-AZ'
UPDATE gpcomp1.gpcust SET Collector = 'EUA NO' WHERE Collector ='EU_NO'
UPDATE gpcomp1.gpcust SET Collector = 'EUA EXPORT' WHERE Collector ='UK EXPORT'
UPDATE gpcomp1.gpcust SET Collector = 'EUA UK_UK' WHERE Collector ='UK_UK1'
UPDATE gpcomp1.gpcust SET Collector = 'EUA UK_UK' WHERE Collector ='UK_UK2'
UPDATE gpcomp1.gpcust SET Collector = 'EUA CM' WHERE Collector ='EU_CM'

UPDATE gpcomp1.gpcoll set team ='EUA' WHERE collcode = 'EU_EXPORT'
UPDATE gpcomp1.gpcoll set team ='EUA' WHERE collcode = 'EUA'

DELETE FROM gpcomp1.gpcoll where collcode = 'CEU_legal'
DELETE FROM gpcomp1.gpcoll where collcode = 'CS-AZ'
DELETE FROM gpcomp1.gpcoll where collcode = 'EU-LEGAL'
DELETE FROM gpcomp1.gpcoll where collcode = 'EU_CM'
DELETE FROM gpcomp1.gpcoll where collcode = 'EU_DE'
DELETE FROM gpcomp1.gpcoll where collcode = 'EU_DM'
DELETE FROM gpcomp1.gpcoll where collcode = 'EU_IT'
DELETE FROM gpcomp1.gpcoll where collcode = 'EU_NL'
DELETE FROM gpcomp1.gpcoll where collcode = 'EU_NO'
DELETE FROM gpcomp1.gpcoll where collcode = 'EU_PO'
DELETE FROM gpcomp1.gpcoll where collcode = 'EU_RO'
DELETE FROM gpcomp1.gpcoll where collcode = 'EU_SP'
DELETE FROM gpcomp1.gpcoll where collcode = 'ME - ET'
DELETE FROM gpcomp1.gpcoll where collcode = 'SSA_BKY'
DELETE FROM gpcomp1.gpcoll where collcode = 'SSA_LEGAL'
DELETE FROM gpcomp1.gpcoll where collcode = 'UK EXPORT'
DELETE FROM gpcomp1.gpcoll where collcode = 'UK_UK1'
DELETE FROM gpcomp1.gpcoll where collcode = 'UK_UK2'
DELETE FROM gpcomp1.gpcoll where collcode = 'W AFR EXP'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-ANGOLA2'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-CABINDA'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-CAMEROO'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-CHAD'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-CONGO'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-GHANA'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-GQ'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-IVORY C'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-MOZAMBI'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-NAMIBIA'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-NIGERIA'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-S AFRIC'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-SENEGAL'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-TANZ'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-UGANDA'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA_KENYA'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA_LIBERIA'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA_NG_LOC'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA_SCREENE'
DELETE FROM gpcomp1.gpcoll where collcode = 'WA-GABON'

DELETE FROM GPCOMP1.GPCOLTM WHERE TEAM IN ('CONT_EU', 'N_SEA_AZER', 'SSA')

--ROLLBACK TRAN