SELECT e.CUSTNO, INVNO, e.AMOUNT_BASE AS BASE_AMT
FROM
(SELECT CASE WHEN ACTION = 'C' THEN 0 - AMOUNT_BASE ELSE AMOUNT_BASE END AS AMOUNT_BASE,
RECEIPT_ID, CUSTNO, INVNO, MODIFIED_ON,
CASE WHEN ACTION = 'C' THEN 0 - AMOUNT ELSE AMOUNT END AS AMOUNT
FROM gpcomp1.GAEXPORT (NOLOCK)
WHERE (OPERATION = 6)) as e
INNER JOIN gpcomp1.GARECEIPT (NOLOCK) as r ON r.RECEIPT_ID = e.RECEIPT_ID
INNER JOIN gpcomp1.GPCUST (NOLOCK) as cust ON e.CUSTNO = cust.CUSTNO
CROSS JOIN GPGLOBAL.GPSYST (NOLOCK) as s
LEFT OUTER JOIN GPGLOBAL.GPCURNCY (NOLOCK) as c ON c.CURRCODE = r.CURRCODE AND c.CLIENT_ID = 1
WHERE (s.SYST_ID = 1)
AND r.RECEIPT_DATE >='2021-08-01'
AND r.RECEIPT_DATE <= '2021-03-31'
--AND cust.COLLECTOR in ('LA - TT')