--select a.*, l.custno, l.INVNO, l.FLEXFIELD11, l.FLEXFIELD14 from 
UPDATE l
SET  l.FLEXFIELD11 = a.FLEXFIELD11, l.FLEXFIELD14 = a.FLEXFIELD14
FROM
(select CUSTNO, INVNO, FLEXFIELD11, FLEXFIELD14 from gpcomp1.ARMAST
union 
select CUSTNO, INVNO, FLEXFIELD11, FLEXFIELD14 from gpcomp1.ARMAST_JDE
) A
LEFT join gpcomp1.ARCONSOLIDATOR c on a.CUSTNO = c.AFFILIATE_NO
join gpcomp1.GPRECL l on a.INVNO = l.INVNO and l.CUSTNO = ISNULL(c.MAIN_NO, a.custno)
where a.FLEXFIELD11 IS NOT NULL or a.FLEXFIELD14 IS NOT NULL

--select a.*, l.custno, l.INVNO, l.FLEXFIELD11, l.FLEXFIELD14 from 
UPDATE l
SET  l.FLEXFIELD11 = a.FLEXFIELD11, l.FLEXFIELD14 = a.FLEXFIELD14
FROM
(select CUSTNO, INVNO, FLEXFIELD11, FLEXFIELD14 from gpcomp1.ARMAST
union 
select CUSTNO, INVNO, FLEXFIELD11, FLEXFIELD14 from gpcomp1.ARMAST_JDE
) A
LEFT join gpcomp1.ARCONSOLIDATOR c on a.CUSTNO = c.AFFILIATE_NO
join gpcomp1.GPRECLLOG l on a.INVNO = l.INVNO and l.CUSTNO = ISNULL(c.MAIN_NO, a.custno)
where a.FLEXFIELD11 IS NOT NULL or a.FLEXFIELD14 IS NOT NULL

