DECLARE @WftUserId varchar(10) = 'E254037'

SELECT 'INSERT INTO Employee (Id, wftid, firstname, middlename, lastname, fullname, title, email, department, manager, address, created, modified, active, displayname, managerid, inserted, updated, hrmsEmployeeID, workNumber, mobileNumber) ' ,
' VALUES ('
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), Id				))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), wftid				))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), firstname			))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), middlename		))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), lastname			))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), fullname			))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), title				))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), email				))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), department		))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), manager			))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), address			))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), created			))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), modified			))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), active			))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), displayname		))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), managerid			))) +  '''', 'NULL') + ','
+ 'DEFAULT ,'   --[Inserted] --ISNULL('''CONVERT(VARBINARY(MAX), REPLICATE('+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), inserted, 1		))) +  ''',10000)', 'NULL') + ','
+ 'DEFAULT ,' --[Updated]
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), hrmsEmployeeID	))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), workNumber		))) +  '''', 'NULL') + ','
+ ISNULL(''''+ LTRIM(RTRIM( CONVERT(VARCHAR(MAX), mobileNumber		))) +  '''', 'NULL') + ')'
from Employee where wftid = @WftUserId

SELECT 'INSERT INTO EconnectEmployeeData (emplid,first_name,middle_name,last_name,second_last_name,descr2,w_region_descr,w_country,w_prod_line_descr,w_product_line,w_sub_prd_ln_descr,position_nbr,position_entry_dt, position_title,reports_to,manager_id,jobcode,w_descr2,w_jobfmly_descr,w_location_descr,defaultJobBonusPercentage,employeeID,managerEmployeeID,inserted, updateId,insertId,w_hpyp_cc_id_descr,w_hpyp_cc_id) VALUES ('
, ISNULL('''' + CONVERT(VARCHAR(MAX), emplid								 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), first_name							 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), middle_name							 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), last_name								 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), second_last_name						 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), descr2								 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), w_region_descr						 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), w_country								 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), w_prod_line_descr						 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), w_product_line						 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), w_sub_prd_ln_descr					 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), position_nbr							 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), position_entry_dt						 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), position_title						 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), reports_to							 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), manager_id							 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), jobcode								 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), w_descr2								 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), w_jobfmly_descr						 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), w_location_descr						 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), defaultJobBonusPercentage				 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), employeeID							 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), managerEmployeeID						 ) + '''',  'NULL') + ','
, ' CONVERT(VARBINARY(8), ''' + CONVERT(varchar(MAX), inserted, 1) + '''),'
+ ISNULL('''' + CONVERT(VARCHAR(MAX), updateId								 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), insertId								 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), w_hpyp_cc_id_descr					 ) + '''',  'NULL') + ','
+ ISNULL('''' + CONVERT(VARCHAR(MAX), w_hpyp_cc_id 							 ) + '''',  'NULL') + ')'
FROM EConnectEmployeeData
WHERE EmployeeID = (select Id from Employee WHERE WftId = @WftUserId)